# FOSUserBundle Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Wiz\UserBundle\Entity\FosUser
    group:
        form:
            type: wizuserbundle_formtype_fosgrouptype
        group_class: Wiz\UserBundle\Entity\FosGroup
    registration:
        form:
            type: wizuserbundle_formtype_usertype

# KnpMenuBundle Configuration
knp_menu:
    twig:
        template: knp_menu.html.twig
    templating: false
    default_renderer: twig
    providers:
        builder_alias: true    # disable the builder-based provider
        container_aware: true

# KnpPaginatorBundle Configuration
knp_paginator:
    page_range: 10
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: WizAdmintoolsBundle:Pagination:sliding.html.twig
        sortable: WizAdmintoolsBundle:Pagination:sortable_link.html.twig

# FMElfinderBundle Configuration
fm_elfinder:
    locale: %locale%
    editor: ckeditor
    fullscreen: true
    include_assets: true
    compression: false
    connector:
        debug: false
        roots:
            uploads:
                driver: LocalFileSystem
                path: uploads
                upload_allow: ['image/png', 'image/jpg', 'image/jpeg', 'application/pdf']
                upload_deny: ['all']
                upload_max_size: 5M

# A2lixTranslationForm Configuration
a2lix_translation_form:
    locales: %locales%
    manager_registry: doctrine
    templating: "WizAdmintoolsBundle:Form:a2lix_translations_widget.html.twig"

# AvalancheImagine Configuration
avalanche_imagine:
    source_root:  %kernel.root_dir%/../web
    web_root:     %kernel.root_dir%/../web
    cache_prefix: uploads/cache
    filters:
        auto_width100:
            type: relative_resize
            options: { widen: 100 }
        auto_height100:
            type: relative_resize
            options: { heighten: 100 }
        thumb100:
            type: thumbnail
            options: { size: [100, 100], mode: outbound , cache_type: public }
        thumb150:
            type: thumbnail
            options: { size: [150, 150], mode: outbound , cache_type: public }
        avatar320:
            type: thumbnail
            options: { size: [320, 320], mode: inset, cache_type: public }
        avatar640:
            type: thumbnail
            options: { size: [640, 640], mode: inset, cache_type: public }